### ISSUE TITLE
Thank you for making your work public :)

### ISSUE THREAD

**Issue by Krande** [aethereng/docker-codeaster#4]
Hey guys, 

thank you for sharing your work on code aster with the public :) This is really awesome!

I was just wondering if you have any plans on publishing some docker images to dockerhub so that others can reference that in their ci build pipeline (like I do for [adapy](https://github.com/Krande/adapy))?

If not, that's perfectly fine:) Then I will just manually push a suitable base-image based on your work (to be used by FEM analysis testing with adapy) to in my krande "channel" on dockerhub :) 

Btw! I am also trying to figure out how to publish code aster on conda (see https://gitlab.com/codeaster/src/-/issues/1). 
The work you have done here will definitively help in that regards :)

**Comment by Jesusbill** [comment]
Hi @Krande thank you for your comment, appreciate it! I hope it can be useful for your great projects and any PR or comments/suggestions are very welcome 
Yes we will definitely publish the images on dockerhub, but better after dealing with this [issue](https://github.com/aethereng/docker-codeaster/issues/5) I just posted.

PS: Great to see you already grabbed it :)
